# Generated by Django 3.2 on 2021-04-22 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0004_alter_tweet_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='photo',
            field=models.CharField(max_length=120),
        ),
        migrations.DeleteModel(
            name='Dag',
        ),
    ]
