# Generated by Django 3.2 on 2021-04-23 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0007_alter_tweet_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='photo',
            field=models.URLField(blank=True, max_length=800),
        ),
    ]
